### PR TITLE
feat(avatars): presence status

### PR DESCRIPTION
**Pull request by jzempel**
- [x] **BREAKING CHANGE?** 

## Description

Removed:
* `.c-avatar--borderless` – avatars no longer have a default single pixel border; images now expand to the full size of the container.
* `.c-avatar.is-disabled` – this state is not reflected in product and doesn't retain strong semantic value.

Added:
* Status modifications:
    * `.c-avatar.is-active`
    * `.c-avatar.is-away`
    * `.c-avatar.is-online`
* `.c-avatar .c-avatar__badge` child element to pair with active/online status.
* `.c-avatar.is-rtl` for alternate badge positioning.
* EXPERIMENTAL styling support for text avatars (similar to https://material-ui.com/components/avatars/#letter-avatars).

## Detail

> Demo is pre-published for review: https://garden.zendesk.com/css-components/avatars/. Use menu controls to observe various state changes.

My [original](https://github.com/zendeskgarden/css-components/commit/3cb08b452760b66ec0b280ad140b19a16f295329#diff-345341b2386edb3b40b7cfb74679de75) take on this was to bake the badge into the avatar as a pseudo element that received its value from a `data-badge` attribute. While this feels more self-contained, I wasn't convinced that it offered important accessibility options.

I think there are (at least) two layouts that support a quality voice-over experience:

```html
<figure class="c-avatar is-active"
    aria-live="polite">
  <img alt="Michael Scott" src="ms.png" />
  <figcaption class="c-avatar__badge"
      aria-label="15 unread notifications"
      role="text">9+</figcaption>
</figure>
```

On badge change, VO will (politely) announce: _"Michael Scott. 15 unread notifications"_. Although it achieves our VO goal in WebKit, the use of `role="text"` is non-standard. Another option is:

```html
<figure class="c-avatar is-active"
    aria-label="the user has five unread messages"
    aria-live="polite"
    role="img">
  <img alt="user" src="user.png" />
  <figcaption class="c-avatar__badge">5</figcaption>
</figure>
```

The second example follows a technique described by the [MDN img role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Role_Img) documentation and would simply announce: _"the user has five unread messages"_.

In the latter case, it could be argued that we might simplify the avatar structure and go back to using the `::after` pseudo – which simplifies dynamic maintenance of the status/badge combo (i.e. leave the badge in place, but remove it's contents when status goes from `active` to `online`, etc.). Just for sake of the argument, here's the simplified `::after` badge HTML:

```html
<figure class="c-avatar is-active"
    aria-atomic="true"
    aria-live="polite"
    data-badge="8">
  <img alt="pam beesly" src="pam.png" />
</figure>
```

Without additional attributes (i.e. `role="img"` + `aria-label`), VO reads modifications to this structure as _"pam beesly 8"_.

p.s. One additional option would be to plant all of the VO content on the badge itself, like this:

```html
<figure class="c-avatar is-active">
  <img alt="dwight schrute" src="ds.png" />
  <figcaption class="c-avatar__badge"
    aria-label="Notifications for Dwight Schrute:"
    role="status">8</figcaption>
</figure>
```

Which would announce _"Notifications for Dwight Schrute: 8"_ upon badge update using heuristics for `aria-live="polite"`.

## Checklist

* [x] :ok_hand: style updates are Garden Designer approved (add the
  designer as a reviewer)
* [x] :globe_with_meridians: component demo is up-to-date (`yarn start`)
* [x] :white_check_mark: all component states are represented
  (`.is-hovered`, `.is-focused`, etc.)
* [x] :arrow_left: renders as expected with reversed (RTL) direction
* [x] :metal: renders as expected sans Bedrock (`?bedrock=false`)
* [ ] :nail_care: ~provides `custom.css` example for modifying the
  primary accent color~
* [x] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11

### CODE REVIEW

**Comment by ryanseddon** [comment]
I think we could have the best of both worlds with this markup:

```html
<figure class="c-avatar is-active"
    aria-atomic="true"
    aria-live="polite"
    data-badge="8">
  <img alt="pam beesly" src="pam.png" />
</figure>
```

Then we document that the alt tag is either the users name, name + status or name + status + notification count. This will need to be handled via each teams translation strings though.

**Comment by jzempel** [comment]
@ryanseddon the issue here is that the content of the `::after` will always be read last. So that means the VO will read “...9+” for notification counts greater than 10. Might not be ideal.

**Comment by ryanseddon** [comment]
I see then perhaps the more verbose markup is fine since the majority will consume this via react which can hide thee details?

**Comment by jzempel** [comment]
I _think_ so. We'll just have to weigh what we can do to make react `<Avatar>` mostly functional out-of-the-box vs. usage documentation required for 100% accessibility.

**Comment by jzempel** [comment]
@jianw3i I took a crack at refining the animations to fall more inline with your spec. See the updated demo: https://garden.zendesk.com/css-components/avatars/. LMK how they are feeling. And please share your animation mock-ups (outside this thread) with @allisonacs. Thanks!

**Comment by jzempel** [comment]
@allisonacs this is now prepared for final design review: https://garden.zendesk.com/css-components/avatars/

**Pull request merged**
