### PR TITLE
fix: remove save-dev from bedrock install instructions

### PR DESCRIPTION
**Pull request by Gwash3189**
- [ ] **BREAKING CHANGE?** 

## Description

removes the `--save-dev` flag from the bed-rock install `README.md` file. 

## Checklist

* [ ] :ok_hand: style updates are Garden Designer approved (add the
  designer as a reviewer)
* [ ] :globe_with_meridians: component demo is up-to-date (`yarn start`)
* [ ] :white_check_mark: all component states are represented
  (`.is-hovered`, `.is-focused`, etc.)
* [ ] :black_circle: renders as expected in "dark" mode
* [ ] :arrow_left: renders as expected with reversed (RTL) direction
* [ ] :nail_care: provides `custom.css` example for modifying the
  primary accent color
* [ ] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11

### CODE REVIEW

**Comment by Gwash3189** [comment]
I have no idea what I'm doing, so let me know if I've missed something. Thanks!

**Comment by austin94** [comment]
👋 Hi @Gwash3189, thanks for the contribution! I've add @jzempel  and @ryanseddon to help with the discussion.

I think we might want to do 2 additional things in this PR:

* Decide what installation directions we want to say
  * I think `npm install --save BLAH` is perfect, but I know there was some discussion of just matching what they have in the NPM registry. 
  * So just `npm install BLAH`
* Whatever we decide we should apply to all of the `README.md` files. 
  * Should be a simple find-replace

Would like anyone else's thoughts though.

**Comment by jzempel** [comment]
I can see why you would want Bedrock to install to `dependencies` vs the others. But I would agree with @austin94 – we should update all the READMEs. Let's match npm's package documentation and just go with the simple: `npm i BLAH`

**Comment by austin94** [comment]
Perfect. So an action item would be:

* Update all `packages/*/README.md` to have the installation convention `npm i PACKAGE_NAME`

Once that's done we will merge it and run a `patch` release on all packages since we need to push a new version if we want NPM to display the updates.

**Comment by jzempel** [comment]
We've got about 50/50 usage between installing to `dependencies` or `devDependencies`. There is a thread in the "#garden" channel that is getting behind the idea of a less opinionated `npm i package-name` (which does a `--save` by default). I'd prefer just sticking with the default we see on every npm package page of `npm i package-name`. @Gwash3189 your newb concerns are still addressed with this syntax.

**Pull request merged**
